version: 2.1

orbs:
  architect: giantswarm/architect@0.13.0
  codecov: codecov/codecov@1.0.2

workflows:
  test:
    jobs:
      - run-tests

      - architect/push-to-docker:
          name: push-app-build-suite-to-quay
          requires:
            - run-tests
          context: architect
          image: "quay.io/giantswarm/app-build-suite"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

jobs:
  run-tests:
    executor: architect/architect
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Execute tests
          command: |
            apk --no-cache add make
            make docker-test

      - codecov/upload:
          file: {{ coverage_report_filepath }}
